#!/bin/bash
# ~/bar.sh
#
# Manuel Nila - Aug 2018

source "$(dirname $0)/config_bar.conf"

dateandtime() {
	echo "$( date '+%A %I:%M %p' ) "
}

batteryinfo() {
	# Using acpi, trim away whitespace and extra chars
	batt="$( acpi | awk '{ print $4 }' | tr '%,' ' ' | xargs )"
	batt_icon="\uf240"

	# Four levels of battery, limited by font awesome free :(
	if [ $batt -gt 90 ]; then
		batt_icon="\uf240"
	elif [ $batt -gt 60 ]; then
		batt_icon="\uf241"
	elif [ $batt -gt 40 ]; then
		batt_icon="\uf242"
	elif [ $batt -gt 20 ]; then
		batt_icon="\uf243"
	else
		batt_icon="\uf244"
	fi
	echo "%{T1}$batt% %{T2}$batt_icon%{T1}"
}

meminfo() {
	echo "$( cat /proc/meminfo | awk '\
	NR < 3 \
	{if (NR == 1) { free=$2; next }} \
	{if (NR == 2) { free-=$2; next }} \
	END \
	{{if ((free/1000/1000) < 1) { printf "%3dMB", (free/1000) }} \
	{if ((free/1000/1000) > 1) { printf "%1.2fGB", (free/1000/1000) }}}'
)"

}

brightness() {
	echo "$( \
		awk '{ if (FNR==NR) 
		{ value=$0; next } { printf "%2.0d", (value / $0 * 100) }}'\
	       	/sys/class/backlight/intel_backlight/brightness \
		/sys/class/backlight/intel_backlight/max_brightness )"
}

volume() {
	state="$( amixer get Master | awk 'END { print $6}' | tr '[]' ' ' | xargs )"
	vol="$( amixer get Master | awk 'END { print $5 }' | tr '[]%' ' ' | xargs)%"
	vol_icon="\uf028"

	if [[ vol -gt 50 && "$state" == "on" ]]; then
		vol_icon="\uf028"
	elif [[ vol -gt 10 && "$state" == "on" ]]; then
		vol_icon="\uf027"	
	elif [[ "$state" == "on" ]]; then
		vol_icon="\uf026"
	else
		vol="mute"
		vol_icon="\uf026"
	fi

	echo "%{T1}$vol %{T2}$vol_icon%{T1}"
}

window_focus() {
	id=$( xprop -root _NET_ACTIVE_WINDOW | awk '{ print $5 }')
	window_name="$( xprop -id $id WM_CLASS | awk '{ print $4 }' | xargs )"

	echo "$window_name"
}

parse_net_wm_name () {		
	echo "$( xprop -id $1 2> /dev/null | awk '/_NET_WM_NAME/' | cut -d '"' -f2 )"
}

spotify_now_playing() {
	if [[ "$1" -ne '' ]]; then
		echo "%{cT2F#6AE368}\uf1bc%{T1} $( parse_net_wm_name $1 ) %{F#FFFFFFr}"
	fi
}

#Status Bar
while :; do
	# Find Spotify Window ID
	if [[ "$(window_focus)" == "Spotify" && $spot_id == '' ]]; then
		 spot_id="$( xprop -root _NET_ACTIVE_WINDOW | awk '{ print $5 }')"	
	fi

	echo -e "%{T3} $(window_focus) $(spotify_now_playing $spot_id) %{r}$(volume)  $(batteryinfo)  $(dateandtime) "
	sleep 2
done
